"""
One-off backfill: run Spotify search for albums that have a Medium-embedded
Spotify link but no `spotify_url` written to the DB — a distinct case from
backfill_spotify.py's original 243-album gap.

`enrich_with_spotify()`'s "skip if a Spotify embed already exists" check only
tests whether *any* type='spotify' media row exists for the album, not
whether that embed is actually the catalogued album itself. When a review is
illustrated with a different song (a single, a later-era track, a preview),
the album silently never gets a real Spotify search at all — confirmed on
#648 Neneh Cherry/Raw Like Sushi (embed was a 2014 "Blank Project" track).
Some of the 26 found this way are actually fine (the embed IS the right
album, it just never got copied into the dedicated spotify_url/cover-art
columns) — this script re-searches and writes the confirmed match regardless,
same as backfill_spotify.py, without touching the existing media rows.

Commits after every album (same resumable, no-lost-progress shape as
backfill_spotify.py). Confident matches go straight to the DB; anything
uncertain or with zero results goes to spotify_manual_review_embedded_gap.md
for a manual look instead of being guessed at.
"""

import json
import time
from pathlib import Path

from db import get_connection, update_album_spotify, export_from_db
from enrich_1001_albums import get_spotify_token, spotify_search_album, REQUEST_DELAY, OUTPUT_FILE

REVIEW_FILE = "spotify_manual_review_embedded_gap.md"


def gap_albums(conn):
    return conn.execute(
        """
        SELECT id, catalog_number, artist, album, year FROM albums
        WHERE spotify_url IS NULL
        AND id IN (SELECT album_id FROM media WHERE type = 'spotify')
        ORDER BY catalog_number
        """
    ).fetchall()


def main():
    conn = get_connection()
    albums = gap_albums(conn)
    print(f"{len(albums)} albums need a Spotify lookup")

    token = get_spotify_token()
    confirmed = 0
    review_rows = []

    for i, a in enumerate(albums, 1):
        label = f"#{a['catalog_number']} {a['artist']} - {a['album']} ({a['year']})"
        try:
            result = spotify_search_album(token, a["artist"], a["album"], str(a["year"]))
        except RuntimeError as e:
            print(f"Stopped early at {label}: {e}")
            break

        if result and result["confident"]:
            update_album_spotify(conn, a["id"], result)
            conn.commit()
            confirmed += 1
            print(f"  [{i}/{len(albums)}] OK  {label}")
        elif result:
            review_rows.append({
                "number": a["catalog_number"], "artist": a["artist"], "album": a["album"],
                "year": a["year"], "status": "uncertain",
                "candidate": f"{result['matched_artist_name']} - {result['matched_album_name']} ({result['matched_release_year']})",
                "candidate_url": result["spotify_url"],
                "album_similarity": result["album_similarity"],
            })
            print(f"  [{i}/{len(albums)}] ??  {label} -> {result['matched_album_name']} (sim={result['album_similarity']})")
        else:
            review_rows.append({
                "number": a["catalog_number"], "artist": a["artist"], "album": a["album"],
                "year": a["year"], "status": "not_found",
                "candidate": None, "candidate_url": None, "album_similarity": None,
            })
            print(f"  [{i}/{len(albums)}] --  {label} -> no results at all")

        time.sleep(REQUEST_DELAY)

    lines = [
        "# Spotify manual review — embedded-gap batch",
        "",
        f"Generated by backfill_spotify_embedded_gap.py. {confirmed} albums "
        f"auto-confirmed, {len(review_rows)} need a manual look.",
        "",
        "| # | Artist | Album | Year | Status | Best candidate found | Similarity |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in review_rows:
        candidate = f"[{r['candidate']}]({r['candidate_url']})" if r["candidate_url"] else "—"
        lines.append(
            f"| {r['number']} | {r['artist']} | {r['album']} | {r['year']} | "
            f"{r['status']} | {candidate} | {r['album_similarity'] if r['album_similarity'] is not None else '—'} |"
        )
    Path(REVIEW_FILE).write_text("\n".join(lines) + "\n", encoding="utf-8")

    albums_out = export_from_db(conn)
    Path(OUTPUT_FILE).write_text(json.dumps(albums_out, indent=2, ensure_ascii=False), encoding="utf-8")

    conn.close()
    print(f"\nDone. {confirmed} confirmed, {len(review_rows)} in {REVIEW_FILE}.")


if __name__ == "__main__":
    main()
