"""
One-off backfill: run Spotify search for the albums that were never enriched
(no Medium-embedded Spotify link, and no spotify_url in the DB yet — see
CLAUDE.md's "Known open items" for how these 243 gap albums came to exist).

Commits after every single album, unlike enrich_with_spotify()'s callers
(which only insert_album() once a whole new-entries batch has finished) —
a 429 mid-run here loses zero already-confirmed matches, and simply re-running
this script picks up where it left off (the WHERE clause only ever selects
albums still missing spotify_url).

Confident matches (album_similarity >= ALBUM_SIM_THRESHOLD) are written
straight to the DB. Everything else — zero results, or a best-guess below
the confidence floor — goes to spotify_manual_review.md instead of being
guessed at automatically, for Ed to check by hand.
"""

import json
from pathlib import Path

from db import get_connection, update_album_spotify, export_from_db
from enrich_1001_albums import get_spotify_token, spotify_search_album, REQUEST_DELAY, OUTPUT_FILE
import time

REVIEW_FILE = "spotify_manual_review.md"


def gap_albums(conn):
    return conn.execute(
        """
        SELECT id, catalog_number, artist, album, year FROM albums
        WHERE spotify_url IS NULL
        AND id NOT IN (SELECT album_id FROM media WHERE type = 'spotify')
        ORDER BY catalog_number
        """
    ).fetchall()


def main():
    conn = get_connection()
    albums = gap_albums(conn)
    print(f"{len(albums)} albums need a Spotify lookup")

    token = get_spotify_token()
    confirmed = 0
    review_rows = []

    for i, a in enumerate(albums, 1):
        label = f"#{a['catalog_number']} {a['artist']} - {a['album']} ({a['year']})"
        try:
            result = spotify_search_album(token, a["artist"], a["album"], str(a["year"]))
        except RuntimeError as e:
            print(f"Stopped early at {label}: {e}")
            break

        if result and result["confident"]:
            update_album_spotify(conn, a["id"], result)
            conn.commit()
            confirmed += 1
            print(f"  [{i}/{len(albums)}] OK  {label}")
        elif result:
            review_rows.append({
                "number": a["catalog_number"], "artist": a["artist"], "album": a["album"],
                "year": a["year"], "status": "uncertain",
                "candidate": f"{result['matched_artist_name']} - {result['matched_album_name']} ({result['matched_release_year']})",
                "candidate_url": result["spotify_url"],
                "album_similarity": result["album_similarity"],
            })
            print(f"  [{i}/{len(albums)}] ??  {label} -> {result['matched_album_name']} (sim={result['album_similarity']})")
        else:
            review_rows.append({
                "number": a["catalog_number"], "artist": a["artist"], "album": a["album"],
                "year": a["year"], "status": "not_found",
                "candidate": None, "candidate_url": None, "album_similarity": None,
            })
            print(f"  [{i}/{len(albums)}] --  {label} -> no results at all")

        time.sleep(REQUEST_DELAY)

    lines = [
        "# Spotify manual review",
        "",
        f"Generated by backfill_spotify.py. {confirmed} albums auto-confirmed, "
        f"{len(review_rows)} need a manual look.",
        "",
        "For each row: check if the candidate (if any) is actually the right album. "
        "If yes, note the correct Spotify album URL; if the candidate is wrong or "
        "missing, either find the right Spotify URL by hand or confirm it's not on "
        "Spotify at all.",
        "",
        "| # | Artist | Album | Year | Status | Best candidate found | Similarity |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in review_rows:
        candidate = f"[{r['candidate']}]({r['candidate_url']})" if r["candidate_url"] else "—"
        lines.append(
            f"| {r['number']} | {r['artist']} | {r['album']} | {r['year']} | "
            f"{r['status']} | {candidate} | {r['album_similarity'] if r['album_similarity'] is not None else '—'} |"
        )
    Path(REVIEW_FILE).write_text("\n".join(lines) + "\n", encoding="utf-8")

    albums_out = export_from_db(conn)
    Path(OUTPUT_FILE).write_text(json.dumps(albums_out, indent=2, ensure_ascii=False), encoding="utf-8")

    conn.close()
    print(f"\nDone. {confirmed} confirmed, {len(review_rows)} in {REVIEW_FILE}.")


if __name__ == "__main__":
    main()
